### ISSUE TITLE
LegioCluster: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by KarimAI7** [WHaasNY/LegioCluster#2]
I am getting this issue when trying to run my .txt file:
`Sorry, file "prev_isolates.txt" not found.
Traceback (most recent call last):
  File "LegioCluster_main.py", line 381, in <module>
    main(input_file)
  File "LegioCluster_main.py", line 262, in main
    if check_job(initials, sp_abbr, isolate, raw_reads_1, raw_reads_2, 
  File "LegioCluster_main.py", line 214, in check_job
    elif isolate in get_isolate_list(SS_dir):
TypeError: argument of type 'NoneType' is not iterable
`

The tutorial file worked fine and I got an output. This issue happened when i tried using the Lpn genomes. I attached the .txt file
[SPF_R_files.txt](https://github.com/WHaasNY/LegioCluster/files/8643837/SPF_R_files.txt)
.

**Comment by WHaasNY** [comment]
Thank you for the comment. The "prev_isolates.txt" is there to ensure that an isolate is not being run twice, which can create a mess when clustering isolates. If the file is not found, you can easily create one by going into the /Genomes/ folder for the species, such as /Genomes/Lpn/, and then enter on the command line “touch prev_isolates.txt”. This will create an (empty) prev_isolates.txt file and should solve the problem. There will be a fix for this in the update to the pipeline.
